### ISSUE TITLE
TezosSwift pod install error

### ISSUE THREAD

**Issue by songproducer** [fortmarek/TezosContracts#1] opened 2019-11-29 14:50 UTC
Hi! I'm trying to follow this tutorial:
https://www.ackee.cz/blog/en/interacting-with-the-tezos-blockchain-on-ios-part-1/

I cloned TezosSwift into the directory and ran:

pod install

but got:

```
[!] Invalid `Podfile` file: undefined method `  pod' for #<Pod::Podfile:0x007fbd3fb7fcd8>.

 #  from /Users/leotreasure/podtezos/Podfile:7
 #  -------------------------------------------
 #  
 >    pod 'TezosSwift'
 #  
 #  -------------------------------------------
```

**Comment by fortmarek** [comment] 2019-11-29 14:56
Hi!
I don't think you need to clone TezosSwift. Also if you could show me the whole `Podfile`, I can tell you a bit more 🙂 

There have been some changes recently, so please feel free to let me know if there are any things that do not work anymore, I will update the tutorial accordingly.

**Comment by songproducer** [comment] 2019-11-29 15:22
I have my podfile as shown in the tut:

```
platform :ios, '10.0'
inhibit_all_warnings!
use_frameworks!

target 'TezosContracts' do

  pod 'TezosSwift'

end
```

**Comment by fortmarek** [comment] 2019-11-29 15:32
What's your cocoapods version? (`pod --version`)? Also you can try eg `pod 'SwiftGen'` to see if the issue is on our side or there is something wrong with your setup. But I tried it locally and everything seemed fine.

You can also try to clone this repository and checkout to branch `part-1` and run `pod install` there; if it succeeds, you can try to see what the differences might be.

**Comment by songproducer** [comment] 2019-11-29 15:37
pod --version
1.8.4

[!] Unknown command: `SwiftGen`

**Comment by songproducer** [comment] 2019-11-29 15:42
Cloning this repository and checking out branch part-1 and pod install worked! I'm sorry I'm not 100% sure how to read the diff should I post it here?

**Comment by fortmarek** [comment] 2019-11-29 15:43
Yeah, please do, I'll have a look at it!

**Comment by songproducer** [comment] 2019-11-29 15:44
Leos-iMac-Pro:TezosContracts leotreasure$ diff . ../podtezos/
Only in ../podtezos/: .DS_Store
Only in .: .git
Only in .: .gitignore
diff ./Podfile ../podtezos/Podfile
2d1
< 
7c6,10
<     pod 'TezosSwift', '~> 1.0'
---
> project '/Users/leotreasure/podtezos/TezosContracts/TezosContracts.xcodeproj'
>   pod "TezosCrypto"
>   
> 
> 
diff ./Podfile.lock ../podtezos/Podfile.lock
1a2,3
>   - Base58Swift (2.1.7):
>     - BigInt (~> 3.1)
4,7c6,8
<   - CryptoSwift (0.13.1)
<   - MnemonicKit (1.3.0):
<     - CryptoSwift (~> 0.13.1)
<   - Result (4.0.1)
---
>   - CryptoSwift (0.14.0)
>   - MnemonicKit (1.3.9):
>     - CryptoSwift (~> 0.14.0)
9,10c10,12
<   - Sodium (0.7.0)
<   - TezosSwift (1.0):
---
>   - Sodium (0.8.0)
>   - TezosCrypto (2.1.3):
>     - Base58Swift (~> 2.1.0)
12,14c14,16
<     - MnemonicKit (~> 1.3.0)
<     - Result (~> 4.0.0)
<     - Sodium (~> 0.7.0)
---
>     - CryptoSwift (~> 0.14.0)
>     - MnemonicKit (~> 1.3.7)
>     - Sodium (~> 0.8.0)
17c19
<   - TezosSwift (~> 1.0)
---
>   - TezosCrypto
20a23
>     - Base58Swift
24d26
<     - Result
27c29
<     - TezosSwift
---
>     - TezosCrypto
29a32
>   Base58Swift: 149c9dd95d8712f00e4695b36baafb3031927256
31,33c34,35
<   CryptoSwift: ff68c35a53e03177d31aaa2c1e8b3e010aeed6cb
<   MnemonicKit: 4f55831a04bc4a24e67b959c715338a529e8acb5
<   Result: a6e784bebf48b471d59cddc1adb81f41f678c487
---
>   CryptoSwift: 35a10419f4dbf0619c13f8c1c180037e115323fa
>   MnemonicKit: 5189df03e224eb6c9b63bc3c6b0623fb1134c62d
35,36c37,38
<   Sodium: c5510cc6f5e1b27858e5f260b5cac80d4a3f9379
<   TezosSwift: 34354847130f242e1020a2a45a7f8264b80dfc99
---
>   Sodium: 63c0ca312a932e6da481689537d4b35568841bdc
>   TezosCrypto: d171c4e2bb51fe35d7378777a0328e566d0118ae
38c40
< PODFILE CHECKSUM: af836a9f22a3d04d0fb5ed5228c082205fae9fb8
---
> PODFILE CHECKSUM: 8c223547b7b0811b8aa25936a24d9c2c419aac9e
Common subdirectories: ./Pods and ../podtezos/Pods
Only in .: README.md
Common subdirectories: ./TezosContracts and ../podtezos/TezosContracts
Only in .: TezosContracts.xcodeproj
Common subdirectories: ./TezosContracts.xcworkspace and ../podtezos/TezosContracts.xcworkspace
Leos-iMac-Pro:TezosContracts leotreasure$

**Comment by fortmarek** [comment] 2019-11-29 15:55
Hm, seems like update of dependencies helped, but the error from the `Podfile` is still weird. 

BTW, if you are working on Xcode 11, the project will not be compilable at the moment, you'd need `pod 'TezosSwift', '~> 1.1'`and bump your platform target to 13.0 

And the addresses in the example do not work anymore since there have been many cycles since then, you can find some working in some block explorer.

If you are interested, I can update the tutorial, but probably not before Monday (I'll have to think a bit more about how to fix the issue that the addresses become useless after they are wiped after a set amount of cycles, so I don't have to keep updating the tutorial).

Considering the issue is fixed now, so closing, but feel free to post additional questions.

**Closed as completed by fortmarek** 2019-11-29 15:55 UTC

**Comment by songproducer** [comment] 2019-11-29 16:01
I'm really interested in learning how to make an iOS app so I can make a branded baking app.

I tried to compile the TezosContract xcode project but got this error:

```
ld: warning: directory not found for option '-F/Users/leotreasure/Library/Developer/Xcode/DerivedData/TezosContracts-dxggtsmgjrfaxqemarmfqaodjeet/Build/Products/Debug-iphonesimulator/Base58Swift'
ld: warning: directory not found for option '-F/Users/leotreasure/Library/Developer/Xcode/DerivedData/TezosContracts-dxggtsmgjrfaxqemarmfqaodjeet/Build/Products/Debug-iphonesimulator/BigInt'
ld: warning: directory not found for option '-F/Users/leotreasure/Library/Developer/Xcode/DerivedData/TezosContracts-dxggtsmgjrfaxqemarmfqaodjeet/Build/Products/Debug-iphonesimulator/CryptoSwift'
ld: warning: directory not found for option '-F/Users/leotreasure/Library/Developer/Xcode/DerivedData/TezosContracts-dxggtsmgjrfaxqemarmfqaodjeet/Build/Products/Debug-iphonesimulator/MnemonicKit'
ld: warning: directory not found for option '-F/Users/leotreasure/Library/Developer/Xcode/DerivedData/TezosContracts-dxggtsmgjrfaxqemarmfqaodjeet/Build/Products/Debug-iphonesimulator/SipHash'
ld: warning: directory not found for option '-F/Users/leotreasure/Library/Developer/Xcode/DerivedData/TezosContracts-dxggtsmgjrfaxqemarmfqaodjeet/Build/Products/Debug-iphonesimulator/Sodium'
ld: warning: directory not found for option '-F/Users/leotreasure/Library/Developer/Xcode/DerivedData/TezosContracts-dxggtsmgjrfaxqemarmfqaodjeet/Build/Products/Debug-iphonesimulator/TezosCrypto'
ld: framework not found Base58Swift
clang: error: linker command failed with exit code 1 (use -v to see invocation)

```
I tried to google the error but not a lot came up. Do you have any idea what could be going on?

I'm using Mac Mojave 10.14.6 and Xcode 10.2.1 btw

**Comment by fortmarek** [comment] 2019-11-29 16:04
Are you opening the `YourProject.xcworkspace`? Otherwise, I'd try a combination of deleting derived data or cleaning the current project.

**Comment by songproducer** [comment] 2019-11-29 16:13
Thanks, I tried opening the xcworkspace file and deleting derived data and now getting some different errors:
```

/Users/leotreasure/TezosContracts/Pods/Sodium/Sodium/GenericHash.swift:16:28: Use of undeclared type 'crypto_generichash_state'
/Users/leotreasure/TezosContracts/Pods/Sodium/Sodium/GenericHash.swift:20:21: Use of unresolved identifier 'crypto_generichash_state'
/Clibsodium.crypto_generichash_update:1:13: Did you mean 'crypto_generichash_update'?
/Clibsodium.crypto_generichash_bytes:1:13: Did you mean 'crypto_generichash_bytes'?
/Clibsodium.crypto_generichash_init:1:13: Did you mean 'crypto_generichash_init'?
/Users/leotreasure/TezosContracts/Pods/Sodium/Sodium/GenericHash.swift:23:17: '&' used with non-inout argument of type 'OpaquePointer?'
/Users/leotreasure/TezosContracts/Pods/Sodium/Sodium/GenericHash.swift:127:13: '&' used with non-inout argument of type 'OpaquePointer?'
/Users/leotreasure/TezosContracts/Pods/Sodium/Sodium/GenericHash.swift:141:13: '&' used with non-inout argument of type 'OpaquePointer?'
CryptoSwift
Command CompileSwift failed with a nonzero exit code
```

**Comment by fortmarek** [comment] 2019-11-29 16:17
Yeah, the project is not compilable with Swift 5 (I think) - you can either lower Swift version to 4 (hopefully that will work, I am not 100 % sure) or you will need to update to your Xcode to 11 (which is probably the better solution anyway) and bump the platform version to iOS 13.0 (I'd like to lower that requirement, but have not had the time, yet)

**Comment by songproducer** [comment] 2019-11-29 16:19
I think it was already trying to use Swift 4 as it said conversion to Swift 5 is available - I tried that but it didn't work. I'll start the update process tonight. Thanks for your help.

**Comment by fortmarek** [comment] 2019-11-29 16:20
No problem! Any additional feedback is more than welcome :)

**Comment by songproducer** [comment] 2019-11-30 07:18
Hi!

I ended up finding a solution to the GenericHash.swift:16:28: Use of undeclared type 'crypto_generichash_state error from here
https://github.com/jedisct1/swift-sodium/issues/177

by adding this to the Podfile:

`pod "Sodium", :git => 'https://github.com/Westacular/swift-sodium.git', :branch => 'fix_xcode10.2'`

The build completed successfully and the simulator shows a white screen.

In the console there are these RPC errors:

```
Getting balance failed with error: rpcFailure(reason: TezosSwift.RPCReason.unexpectedRequestFormat(message: ""))
Sending Tezos failed with error: rpcFailure(reason: TezosSwift.RPCReason.unexpectedRequestFormat(message: ""))

```

Do you know how I can connect this to my Carthagenet node?

**Comment by fortmarek** [comment] 2019-11-30 09:14
Yeah, just change `TezosClient(remoteNodeURL: URL(string: "https://rpcalpha.tzbeta.net/")!)` to the node of your choice.

**Comment by songproducer** [comment] 2019-11-30 09:58
Thanks!
I'm getting this now:
```
TezosContracts[17490:1244728] Task <4D805D8F-91D9-4574-AECD-FA6FAB752012>.<1> finished with error [-1002] Error Domain=NSURLErrorDomain Code=-1002 "unsupported URL" UserInfo={NSUnderlyingError=0x600001754480 {Error Domain=kCFErrorDomainCFNetwork Code=-1002 "(null)"}, NSErrorFailingURLStringKey=///chains/main/blocks/head/context/contracts/KT1DwASQY1uTEkzWUShbeQJfKpBdb2ugsE5k/balance, NSErrorFailingURLKey=///chains/main/blocks/head/context/contracts/KT1DwASQY1uTEkzWUShbeQJfKpBdb2ugsE5k/balance, NSLocalizedDescription=unsupported URL}
Getting balance failed with error: rpcFailure(reason: TezosSwift.RPCReason.noData)
2019-11-30 17:57:45.036937+0800 TezosContracts[17490:1244728] Task <B5F5E110-22C7-45FC-AAD1-90B940819D54>.<2> finished with error [-1002] Error Domain=NSURLErrorDomain Code=-1002 "unsupported URL" UserInfo={NSUnderlyingError=0x600001754450 {Error Domain=kCFErrorDomainCFNetwork Code=-1002 "(null)"}, NSErrorFailingURLStringKey=///chains/main/blocks/head, NSErrorFailingURLKey=///chains/main/blocks/head, NSLocalizedDescription=unsupported URL}
2019-11-30 17:57:45.037173+0800 TezosContracts[17490:1244728] Task <50D7AF8B-F6C5-4482-BFAA-4D27D5ED61EB>.<3> finished with error [-1002] Error Domain=NSURLErrorDomain Code=-1002 "unsupported URL" UserInfo={NSUnderlyingError=0x600001756790 {Error Domain=kCFErrorDomainCFNetwork Code=-1002 "(null)"}, NSErrorFailingURLStringKey=///chains/main/blocks/head/context/contracts/tz1WRFiK6eGNvP3ioWkWeP6JwDaQjj95opnQ/counter, NSErrorFailingURLKey=///chains/main/blocks/head/context/contracts/tz1WRFiK6eGNvP3ioWkWeP6JwDaQjj95opnQ/counter, NSLocalizedDescription=unsupported URL}
2019-11-30 17:57:45.037385+0800 TezosContracts[17490:1244728] Task <06C927C0-DCCD-42DD-8DED-6E2B630BDF55>.<4> finished with error [-1002] Error Domain=NSURLErrorDomain Code=-1002 "unsupported URL" UserInfo={NSUnderlyingError=0x6000017567c0 {Error Domain=kCFErrorDomainCFNetwork Code=-1002 "(null)"}, NSErrorFailingURLStringKey=///chains/main/blocks/head/context/contracts/tz1WRFiK6eGNvP3ioWkWeP6JwDaQjj95opnQ/manager_key, NSErrorFailingURLKey=///chains/main/blocks/head/context/contracts/tz1WRFiK6eGNvP3ioWkWeP6JwDaQjj95opnQ/manager_key, NSLocalizedDescription=unsupported URL}
Sending Tezos failed with error: injectError(reason: TezosSwift.InjectReason.missingMetadata)

```

**Comment by fortmarek** [comment] 2019-11-30 10:06
Does the contract you are calling this for exist?

Also, try the call in console, something like this to double check:
`curl https://rpcalpha.tzbeta.net/chains/main/blocks/head/context/contracts/KT1CLxwwULwPQS5SDeSCdhgKv4VmCxRygqvi/balance`

**Comment by songproducer** [comment] 2019-11-30 10:49
Thanks for the curl tip! I was just using the default contract that came with the github code. I will try another contract tonight.
